### ISSUE TITLE
Projekt Kompiliert nicht!

### ISSUE THREAD

**Issue by Wiredaemon** [ProPra16/programmierpraktikum-abschlussprojekt-zenamike#16]
Hallo ihr alle.
Auch wenn euer Code in großen Teilen sehr übersichtlich ist, _**er kompiliert nicht!**_

Ich habs mit gradle probiert, aber auch wenn ich das ganze in eclipse importiere klappt es nicht, denn es fehlt zB einfach die methode pluginLoader() in der Klasse PluginLoader!

Korrigiert das ganze bitte bis Mittwoch.

Hier mein gradle Konsolen output.

**Comment by Wiredaemon** [comment]
$ ./gradlew clean build
:clean
:compileJavaC:\Users\Chris\Downloads\programmierpraktikum-abschlussprojekt-zenamike-master\programmierpraktikum-abschlussprojekt-zenamike-master\src\main\java\de\hhu\propra\tddt\controller\SettingsController.java:48: error: cannot find symbol
            PluginLoader.pluginLoader().activateBabystep(true);
                        ^
  symbol:   method pluginLoader()
  location: class PluginLoader
C:\Users\Chris\Downloads\programmierpraktikum-abschlussprojekt-zenamike-master\programmierpraktikum-abschlussprojekt-zenamike-master\src\main\java\de\hhu\propra\tddt\controller\SettingsController.java:60: error: cannot find symbol
            PluginLoader.pluginLoader().activateBabystep(false);
                        ^
  symbol:   method pluginLoader()
  location: class PluginLoader
C:\Users\Chris\Downloads\programmierpraktikum-abschlussprojekt-zenamike-master\programmierpraktikum-abschlussprojekt-zenamike-master\src\main\java\de\hhu\propra\tddt\controller\SettingsController.java:68: error: cannot find symbol
            PluginLoader.pluginLoader().activateTracker(true);
                        ^
  symbol:   method pluginLoader()
  location: class PluginLoader
C:\Users\Chris\Downloads\programmierpraktikum-abschlussprojekt-zenamike-master\programmierpraktikum-abschlussprojekt-zenamike-master\src\main\java\de\hhu\propra\tddt\controller\SettingsController.java:73: error: cannot find symbol
            PluginLoader.pluginLoader().activateTracker(false);
                        ^
  symbol:   method pluginLoader()
  location: class PluginLoader
C:\Users\Chris\Downloads\programmierpraktikum-abschlussprojekt-zenamike-master\programmierpraktikum-abschlussprojekt-zenamike-master\src\main\java\de\hhu\propra\tddt\controller\TDDController.java:67: error: cannot find symbol
            PluginLoader.pluginLoader().stopAllPlugins();
                        ^
  symbol:   method pluginLoader()
  location: class PluginLoader
C:\Users\Chris\Downloads\programmierpraktikum-abschlussprojekt-zenamike-master\programmierpraktikum-abschlussprojekt-zenamike-master\src\main\java\de\hhu\propra\tddt\controller\TDDController.java:94: error: cannot find symbol
            InformationCore.informationCore().getCompileManager().compileTest(InformationCore.informationCore().getTestManager().getText());
                                                                 ^
  symbol:   method compileTest(String)
  location: class Object
C:\Users\Chris\Downloads\programmierpraktikum-abschlussprojekt-zenamike-master\programmierpraktikum-abschlussprojekt-zenamike-master\src\main\java\de\hhu\propra\tddt\controller\TDDController.java:95: error: cannot find symbol
            System.out.println("ERROR in TEST: "+InformationCore.informationCore().getCompileManager().getCompileResultList());
                                                                                                      ^
  symbol:   method getCompileResultList()
  location: class Object
C:\Users\Chris\Downloads\programmierpraktikum-abschlussprojekt-zenamike-master\programmierpraktikum-abschlussprojekt-zenamike-master\src\main\java\de\hhu\propra\tddt\controller\TDDController.java:107: error: cannot find symbol
            InformationCore.informationCore().getCompileManager().compileTest(InformationCore.informationCore().getTestManager().getText());
                                                                 ^
  symbol:   method compileTest(String)
  location: class Object
C:\Users\Chris\Downloads\programmierpraktikum-abschlussprojekt-zenamike-master\programmierpraktikum-abschlussprojekt-zenamike-master\src\main\java\de\hhu\propra\tddt\controller\TDDController.java:108: error: cannot find symbol
            InformationCore.informationCore().getCompileManager().compileCode(InformationCore.informationCore().getCodeManager().getText());
                                                                 ^
  symbol:   method compileCode(String)
  location: class Object
C:\Users\Chris\Downloads\programmierpraktikum-abschlussprojekt-zenamike-master\programmierpraktikum-abschlussprojekt-zenamike-master\src\main\java\de\hhu\propra\tddt\controller\TDDController.java:109: error: cannot find symbol
            System.out.println("ERROR in CODE: " + InformationCore.informationCore().getCompileManager().getCompileResultList());
                                                                                                        ^
  symbol:   method getCompileResultList()
  location: class Object
C:\Users\Chris\Downloads\programmierpraktikum-abschlussprojekt-zenamike-master\programmierpraktikum-abschlussprojekt-zenamike-master\src\main\java\de\hhu\propra\tddt\controller\TDDController.java:122: error: cannot find symbol
            InformationCore.informationCore().getCompileManager().compileTest(InformationCore.informationCore().getTestManager().getText());
                                                                 ^
  symbol:   method compileTest(String)
  location: class Object
C:\Users\Chris\Downloads\programmierpraktikum-abschlussprojekt-zenamike-master\programmierpraktikum-abschlussprojekt-zenamike-master\src\main\java\de\hhu\propra\tddt\controller\TDDController.java:123: error: cannot find symbol
            InformationCore.informationCore().getCompileManager().compileCode(InformationCore.informationCore().getCodeManager().getText());
                                                                 ^
  symbol:   method compileCode(String)
  location: class Object
C:\Users\Chris\Downloads\programmierpraktikum-abschlussprojekt-zenamike-master\programmierpraktikum-abschlussprojekt-zenamike-master\src\main\java\de\hhu\propra\tddt\controller\TDDController.java:124: error: cannot find symbol
            System.out.println("ERROR in REFACTOR: " + InformationCore.informationCore().getCompileManager().getCompileResultList());
                                                                                                            ^
  symbol:   method getCompileResultList()
  location: class Object
13 errors
 FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':compileJava'.
  
  > Compilation failed; see the compiler error output for details.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.239 secs

**Comment by Wiredaemon** [comment]
@ProPra16/zenamike

**Comment by shaman78** [comment]
👍

**Comment by zeljkobekcic** [comment]
Ist gefixt worden.

Aus irgendwelchen Gruenden war eine Methode nicht drinnen und eine Variable nicht ihrer eigentlichen Klasse zugeordnet worden.

Bei mir compiliert es nun mit
`./gradlew build` oder halt wie du es machst.

**Comment by Wiredaemon** [comment]
nope

**Comment by Wiredaemon** [comment]
$ ./gradlew clean build
:clean
:compileJava
:processResources
:classes
:jar
:assemble
:compileTestJava
:processTestResources
:testClasses
:test

de.hhu.propra.tddt.test.classnameparsertesting.TestClassNameParser > testParsingStrictfpClassName FAILED
    java.nio.file.InvalidPathException at TestClassNameParser.java:57

de.hhu.propra.tddt.test.classnameparsertesting.TestClassNameParser > testParsingAbstractClassName FAILED
    java.nio.file.InvalidPathException at TestClassNameParser.java:33

de.hhu.propra.tddt.test.classnameparsertesting.TestClassNameParser > testParsingFinalClassName FAILED
    java.nio.file.InvalidPathException at TestClassNameParser.java:81

7 tests completed, 3 failed
:test FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':test'.
  
  > There were failing tests. See the report at: file:///C:/Users/Chris/Downloads/programmierpraktikum-abschlussprojekt-zenamike-master/programmierpraktikum-abschlussprojekt-zenamike-master/build/reports/tests/index.html
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 19.371 secs

**Comment by zeljkobekcic** [comment]
Die Sache ist das travis es passen lässt und auf meinem arch linux geht es auch durch. 

Ich Tag hier einfach mal dem zuständigen 
@Schiggy69

**Comment by Wiredaemon** [comment]
hab mal angesehen was da schief läuft
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/Chris/Downloads/.....

Das Problem liegt in
`URL url = getClass().getResource("/HelloWorld.java");`
           `path = Paths.get(url.getPath());`

Denn Url.getPath() gibt einen Pfad nicht nach dem Schema aus wie Windows Pfade behandelt.

siehe
http://stackoverflow.com/questions/6164448/convert-url-to-normal-windows-filename-java

**Comment by Wiredaemon** [comment]
Unter unix-basierten Betriebssystemen macht das keinen Unterschied, da "/" das root Verzeichnis ist und da das ganze dann passt.

Man könnte jetzt sagen, es liegt am bösen Windows, da alle anderen gängigen Betriebsysteme das so machen, oder auch daran, dass man mit Unix-basierten Betriebssystemen einfach Glück hat, dass es gerade so funktioniert.

Mit whitespaces im Pfad wirds aber auch unter Unix inkompatibel.. Die sind dann nämlich %20 statt " "

**Comment by Wiredaemon** [comment]
Mein Vorschlag:
Man nutzt java.io.File
das ist kein Platformabhängiger String sondern extra ne Abstraktion genau für dieses Problem. Wenns damit bei euch klappt, klappts auch wo anders.

**Comment by ghost** [comment]
Ich hab mich nicht mit gradle befasst, aber laut @zeljkobekcic funktioniert das nur so. Hast du den resources Ordner in test/resources auch in deiner IDEA als Resources markiert?

Ich hab das nun wie im stackoverflow link gelöst indem die URL zu ner URI und dann zu nem PATH gecastet wird. Auf Travis passed is immer noch.

**Comment by shaman78** [comment]
👍

**Comment by Wiredaemon** [comment]
Nein, das Problem ist nicht, dass die Datei nicht wirklich da ist.
Das Problem ist, dass der Pfad, so wie ihr ihn angebt kein gültiger Windows Pfad ist.

hier ein auszug aus dem testergebnis. Der slash vor dem C ist immernoch da:
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/Chris/Downloads/programmierpraktikum-abschlussprojekt-zenamike-master/folder with whitespaces/build/resources/test/HelloWorld.java

Aber gut. ich habe das Projekt jetzt einmal ohne tests bauen lassen und mir angesehen.
Das mit dem Pfad in den Tasks ist sehr umständlich. Da wäre ein FileChooser sehr schön gewesen.
Und wenn ich dann wirklich einen Test mit Implementierung schreiben möchte, gehts nicht weiter und es fliegen mir exceptions um die Ohren.

**Comment by Wiredaemon** [comment]
Hier der Konsolen Output wenn ich einfach nur beim RomanNumbers kata den vorgefertigten Code so lasse wie er ist und auf compile drücke:

C:\Users\Chris\Downloads\programmierpraktikum-abschlussprojekt-zenamike-master\folder with whitespaces\src\main\resources\examlpleTasks\ExerciseRoman.xml
Compile
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1774)
        at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1657)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Node.fireEvent(Node.java:8411)
        at javafx.scene.control.Button.fire(Button.java:185)
        at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
        at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
        at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
        at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
        at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
        at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
        at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415)
        at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
        at com.sun.glass.ui.View.notifyMouse(View.java:937)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
        at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
        at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1769)
        ... 48 more
Caused by: java.lang.IllegalArgumentException: You have to set the CompileManager before you can pass it
        at de.hhu.propra.tddt.informationcore.InformationCore.getCompileManager(InformationCore.java:102)
        at de.hhu.propra.tddt.controller.TDDController.handleCompileButton(TDDController.java:94)
        ... 58 more

**Comment by zeljkobekcic** [comment]
Warte mal, ich versuche es mal bei mir.

# 

@Wiredaemon 

EDIT:
Ich habe eben nen Hotfix gemacht.
Bei mir unter Windoof 10 funktionert das und ich bekomme den ganzen Error nicht.

**Comment by shaman78** [comment]
@zeljkobekcic Ich bekomm grad 
Exception in thread "main" java.lang.NullPointerException
    at de.hhu.propra.tddt.settings.Settings.loadSettings(Settings.java:58)
    at de.hhu.propra.tddt.settings.Settings.<init>(Settings.java:44)
    at de.hhu.propra.tddt.settings.SettingsManager.<init>(SettingsManager.java:15)

**Comment by zeljkobekcic** [comment]
Diese paar Zeilen sagen viel über die Fehlerquelle(n) aus oder die Ursache.

**Comment by ghost** [comment]
Ohne deinen lokalen Code kann man da nicht wirklich erraten was da schief läuft.

**Comment by shaman78** [comment]
Das sind alle die ich bekomme :/

**Comment by shaman78** [comment]
Komm ma in dein Ts @zeljkobekcic

**Comment by zeljkobekcic** [comment]
Mach für heute Nacht Feierabend. Gute Nacht /Morgen

**Comment by shaman78** [comment]
komm schon noch 10 min ich will heut noch weitermachen ...

**Comment by shaman78** [comment]
Das Problem ist in TDDController wenn ich die linked liste mit .get().get() nutze, wodurch ich eine Nullpointer bekomme, wobei ich eigentlich das erste Element aus der ersten Liste der Linkedlists bekommen sollte (laut kevin)

![nullpoint](https://cloud.githubusercontent.com/assets/10478748/16898129/73357188-4bca-11e6-9217-72ca7880baf1.jpg)

[http://s2.quickmeme.com/img/48/48db2a3da3e6afc7c925015eb6eed803bf6e28ed82ce79e2b49229e84f45dc47.jpg](url)

**Comment by shaman78** [comment]
Ich brauche immer noch Hilfe, da ich die CompilationResults nicht übergeben bekomme bzw. nur klammern [] oder [[] []]  oder [[] [] []]...
Damit kann ich schlecht prüfen ob der Compilervorgang gelungen ist oder nicht... 
Und somit auch nicht in die nächste Phase gehen...

**Comment by shaman78** [comment]
System.out.println(InformationCore.informationCore().getCompileManager().getCompileResultList().get(0).toString());
CompileContent .get(0): []

System.out.println(InformationCore.informationCore().getCompileManager().getCompileResultList().toString());
CompileContent : [[]]

System.out.println(InformationCore.informationCore().getCompileManager().getCompileResultList().get(0).get(0).toString());

Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1762)
    at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1645)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Node.fireEvent(Node.java:8216)
    at javafx.scene.control.Button.fire(Button.java:185)
    at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
    at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
    at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3724)
    at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3452)
    at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1728)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2461)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:348)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:273)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:382)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:553)
    at com.sun.glass.ui.View.notifyMouse(View.java:925)
Caused by: java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
    at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1757)
    ... 43 more
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
    at java.util.LinkedList.get(LinkedList.java:476)
    at de.hhu.propra.tddt.controller.TDDController.handleCompileButton(TDDController.java:91)
    ... 53 more

**Comment by ghost** [comment]
Debug das bitte endlich und schau nach ob:
- der Eingabestring nicht leer ist
- ob alles richtig compiliert wird (sprich Jens API gecalled wird)
- Was genau in die Ergebnisliste geschrieben wird

Außerdem:
![image](https://cloud.githubusercontent.com/assets/10684523/16964994/5c6c2b00-4dfe-11e6-9471-3837f5bbb94a.png)

Sprich für den Fall, dass der Code einfach Müll ist, musst du dann abfangen, wenn das Ganze nen Nullpointer wirft.

"System.out.println(InformationCore.informationCore().getCompileManager().getCompileResultList().get(0).get(0).toString());"<- Du castest da einen String zu einem String, vielleicht wirft das ja auch Fehler.

Was ist eigentlich CompileContent?

**Comment by shaman78** [comment]
getCompileResultList = Compile content

**Comment by shaman78** [comment]
Wie wärs wenn wir mal wieder zusammen an der Implementierung arbeiten würden und nicht nur ich....
Das ding is wenn eure Sachen nicht Funktionieren und wir hier nichts hinbekommen dann werden wir ALLE das Projekt scheinbar nicht bestehen... (siehe ISSUE 2)

Ich bin ab 15:30 in Zelijko's TS und versuche i-wie i-was zu fixen aber ich kann auch nicht zaubern...
Mit der Einstellung GUI ist dein Problem kommen wir nicht weiter ...
Wenn eure Sachen nicht richtig oder nur zum Teil funktionieren kann ich leider auch nichts machen...

**Comment by shaman78** [comment]
SO ich glaub ich bin dem Problem näher gekommen.
Das ding ist es gibt einen bug im Compiler er bekommt zwar den Text aber er verarbeitet ihn nicht richtig...

**Comment by shaman78** [comment]
compileResults.setTestResults(testComp);
compileResults.errorStringInit(codeComp, compilationTestUnit);
werden beide scheinbar nicht ausgeführt!

@Schiggy69 ich bräuchte deine Hilfe

**Comment by ghost** [comment]
> Das grundlegende Problem ist grade das der Compiler nicht wirklich compilt und ich nur leere Strings bzw. NULL bekomme wodurch ich nicht verifizieren kann ob der Test bestanden wurde oder nicht, somit kann ich nicht an der Implementierung der anderen Sachen arbeiten,

Hast du mein letztes Kommentar in diesem Thread gelesen, auch das Bild mit Jens? Da steht doch alles.

Also, ich weiß immer noch nicht ob du mal debuggt hast oder nicht, also sag ich das jetzt zum letzten Mal: Debugge bitte, damit du siehst wo die Fehler herkommen, nicht per sout(wert1), sout(wert2) sondern mit _Breakpoints_. 

Du warst von Anfang an zuständig für die GUI und warst dir im klaren, dass dort am Ende alles zusammenläuft. Ich persönlich finde es etwas erstaunlich, dass du 3 Wochen dafür gebraucht hast, bis etwas lauffähiges online kam, vor allem, weil du mit einem Scenebuilder arbeitest in dem man sich alles zusammen klicken kann. Aber gut, wenn es das erste Mal ist, dauert es schon länger das ist auch verständlich, aber bedenke mal, dass wir drei Wochen auf die GUI gewartet haben. 

Du hast vor zwei Wochen gesagt, "Ich kann noch nichts von euch implementieren, ihr habt ja noch nichts" darauf hin hab ich dir geraten einfach Platzhalter einzubauen, aber eine laufende GUI (man sieht etwas, aber sie kann noch nichts) hatten wir immer noch nicht. Die Funktionalität der GUI hat nichts mit dem Aussehen zu tun. So wie die GUI momentan aussieht, brauch die keine Anbindung an das Backend um so auszusehen. Natürlich kann man dann noch nichts mit dem Programm anfangen, aber wir hätten schon mal eine GUI gehabt.

Ich weiß nicht, wie es bei dir aussieht aber ich hab am **Montag & Dienstag** eine Klausur geschrieben und schreibe nächste Woche Info II. Ich hoffe, es ist dann klar, dass ich momentan wenig Zeit habe, dir zu helfen bzw. es ist eigentlich kein helfen, denn meistens ich wiederhole nur, was wir in Info I gelernt haben. Dieses Projekt ist wichtig für uns viele von uns, zumindestens ich brauch die 10 CP für mein Bafög. 

Ich will dir nichts unterstellen, aber es ist schon etwas unvorteilhaft, wenn man sich in Propra Übungen setzt und WoW spielt, dann aber später genau die Probleme hat, die in der Übung behandelt wurden.

**Lösungsvorschläge:**

**-Fehlerhaften Code:**
Da ich absolut nicht weiß, wie du versuchst meine Sachen und auch @zeljkobekcic Sachen zu implementieren und ich auch nicht wirklich groß Lust habe, mir das per Teamviewer in Slow-Motion anzuschauen, wäre also mein Vorschlag, dass du es auf eine eigene Branch packst und es dann auf die Branch pushst damit Zeljiko und ich sehen was du versuchst. Außerdem zerschießen wir uns so nicht den Master und wir haben ne okay-ish Version auf die man immer noch zugreifen kann.
Mit der Branch kann _sogar ich_ das Ganze für dich debuggen.

Falls du nicht weiß wie das geht, ich schreibs dir hier nochmal hin:

Wie macht man eine Branch:
- _git checkout -b [name_of_your_new_branch]_

Wie wechsel ich zwischen master und [branch]?
- _git checkout [master]_
- _git checkout [name_of_your_new_branch]_

Wie pushe ich auf meine Branch:
- _git push origin [name_of_your_new_branch]_

Es kann sein, dass git beim wechseln der Branch von dir verlangt, dass du deine Changes am Projekt entweder commitest oder stashest, im Normalfall tut man das auch. Wenn du noch nichts commitet (nicht gepusht!) hast, sollte git dabei auch nicht meckern.

**\- Plugins in die GUI einbauen:**
Mach doch einfach ne Vbox ganz oben in die TDDT Scene, in der man "on the fly" die Plugins per Checkbox aktivieren oder deaktivieren kann. Oder einen Button mit dem man wieder ins Menü kommt (aber seine Arbeit nicht verliert).

**Comment by ghost** [comment]
> compileResults.setTestResults(testComp);
> compileResults.errorStringInit(codeComp, compilationTestUnit);
> werden beide scheinbar nicht ausgeführt!

Schauen wir uns mal meinen Code an:

```
protected LinkedList<String> compileTest(String testCode)throws ClassNameParserException {
        boolean isARealTest = true;
        String testName = ClassNameParser.getClassName(testCode);
        CompilationUnit compilationTestUnit = new CompilationUnit(testName, testCode, isARealTest);
        compilationUnitName = "compilationTestUnit";
        testCompilerInit(compilationTestUnit);
        compileResults.setTestResults(testComp);
        compileResults.errorStringInit(codeComp, compilationTestUnit);

        return compileResults.getTestResults();
    }
```

`String testName = ClassNameParser.getClassName(testCode);`
Zieht den Klassennamen aus der Testdatei (Mögliche Fehlerquelle)

`CompilationUnit compilationTestUnit = new CompilationUnit(testName, testCode, isARealTest);`
Fehlt der Klassenname, wird das nicht ausgeführt.

 `compilationUnitName = "compilationTestUnit";`
Das ist unwichtig, ist mir beim Aufräumen entgangen.

`testCompilerInit(compilationTestUnit);`
Wird compilationTestUnit nicht initializiert, ist hier keine Com Unit vorhanden -> Kein Compiler

```
compileResults.setTestResults(testComp);
        compileResults.errorStringInit(codeComp, compilationTestUnit);
```

Gibts keinen Compiler, geht das hier nicht.

EDIT:
Das ist zwar nur geraten, aber wenn du es auf eine Branch pusht, kann ich das besser nachvollziehen

**Comment by shaman78** [comment]
Ich werd dazu keinen Kommentar abgeben.
Keine lust und zeit jetzt noch nen Streit anzufangen bzw. weiter zu führen.

**Comment by ghost** [comment]
Ich hab gar keinen Streit angefangen bzw. anfangen wollen, sondern einfach meiner Meinung nach Fakten dargelegt und Lösungen vorgeschlagen. Aber okay.

**Comment by shaman78** [comment]
Naja "Fakten" aber okay... WoW in der einen Übung die wir zusammen hatten und in der ich schon mit allem fertig war seh ich jetzt nicht als Fakten. Aber okay.
Aber is jetzt auch egal Hauptsache wir kommen weiter und will das jetzt nich mehr vertiefen...
